---
blank_issues_enabled: false
contact_links:
- name: Potentially exploitable issue
  url: https://discord.gg/galacon-602434888880095242
  about: "Please join the Galacon server if you haven't already and send Meadowsys#8534 a DM (if you need help, @mention me in #general so I can help)"
- name: Discord
  url: https://discord.gg/galacon-602434888880095242
  about: Invite to galacon's discord server.
