---
name: CI
on:
  push:
    branches:
    - "**"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: install pnpm
      uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd # v2.2.1

    - name: install node
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # 3.3.0
      with:
        node-version: v18.4.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: build
      run: pnpm run build


  lint:
    name: lint
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: install pnpm
      uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd # v2.2.1

    - name: install node
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # 3.3.0
      with:
        node-version: v18.4.0
        cache: pnpm

    - name: install dependencies
      run: pnpm i

    - name: lint
      run: pnpm run lint

  deploy:
    name: deploy to heroku
    runs-on: ubuntu-22.04
    needs:
    - build
    - lint
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - name: checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

    - name: build container
      run: podman build . -t canni --format docker

    - name: authenticate to heroku docker registry
      run: podman login -u ${{ secrets.HEROKU_API_USERNAME }} -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com

    - name: push container to heroku
      run: |
        podman tag canni registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/canni
        podman push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/canni

    - name: release
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} canni
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
